### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by mahammad-mostafa** [mahammad-mostafa/food-recipes#11]
- We are a team of two (@mahammad-mostafa & @obibaadoma)
- Check our project tasks from [here](https://github.com/users/mahammad-mostafa/projects/3)

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @mahammad-mostafa and @obibaadoma,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kanban boards should be designed so that all the specifics of a project are well spelled out without referring to the broader requirements. While you are free to include additional requirements for your project, the basic project descriptions must be clearly defined to avoid confusion or mixing up details. Most of your tasks do not have summaries or descriptions that depict the specifics or the technicalities of the project requirements. Kindly ensure the specifics of the project are part of the descriptions.

  For example, what this task describes is somewhat different from the original description and there is no other task that perfectly captures the details of the required task.

  Your task description | Original task description
  :---:|:---:
  ![image](https://github.com/mahammad-mostafa/food-recipes/assets/36542986/f56851e8-2123-47d6-8315-184ecd6ae30a) | ![image](https://github.com/mahammad-mostafa/food-recipes/assets/36542986/a55c0224-db09-4b54-b0f6-1c4318a1201c)

- [ ] I could not find any issues that are intended for these two tasks.

  Navigation task | General shopping list task
  :---:|:---:
  ![image](https://github.com/mahammad-mostafa/food-recipes/assets/36542986/8ed3c044-9cfe-4fbb-938f-a48b3fdf8cbb) | ![image](https://github.com/mahammad-mostafa/food-recipes/assets/36542986/fb34f679-37dc-4a08-8d63-e31b10776643)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danmainah** [comment]
Hi @mahammad-mostafa and @obibaadoma , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️  Implemented the change requested to add a card for `a navigation menu` task.

 # Required Changes ♻️

- [ ] @Team Great work implementing some of the changes requested, however as the previous reviewer noted I couldn't find a task for the `General Shopping List View`, kindly consider adding it.
![image](https://github.com/mahammad-mostafa/food-recipes/assets/61408860/e946b629-3d75-42e9-a5f5-4702862bb1ce)

- [ ] @Team, as previously requested, kindly consider changing the title and description of the cards to match with the tasks from [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md), this will ensure you implement all project requirements and as a part of project requirement as shown below:
![image](https://github.com/mahammad-mostafa/food-recipes/assets/61408860/edd795cc-7f7d-419d-af75-9c06e14a475b)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mahammad-mostafa** [comment]
Hi @danmainah, Thanks for the review. However, we are a bit confused about what exactly is a missing food item inside a recipe. Since the user creates his own food items and then create a recipe to add food items from his own list then what is missing here?

For the shopping list it is mentioned in the card titled navigation & shopping already. I will change the title to match with the content better

Thanks

**Comment by danmainah** [comment]
> Hi @danmainah, Thanks for the review. However, we are a bit confused about what exactly is a missing food item inside a recipe. Since the user creates his own food items and then create a recipe to add food items from his own list then what is missing here?
> 
> For the shopping list it is mentioned in the card titled navigation & shopping already. I will change the title to match with the content better
> 
> Thanks

@mahammad-mostafa I can see it, kindly implement the other request, I would highly recommend if possible you make each task have its card.

**Comment by mahammad-mostafa** [comment]
No problems @danmainah working on it. However, can you explain the requirement of missing food items in the recipe here (project requirements)? It is very confusing for us to implement.
My question is:
Since the user creates his own food items and then create a recipe to add food items from his own list then what is the food items missing here?
I am asking about the meaning of this specific task in terms of feature implementation.

**Comment by danmainah** [comment]
> No problems @danmainah working on it. However, can you explain the requirement of missing food items in the recipe here (project requirements)? It is very confusing for us to implement. My question is: Since the user creates his own food items and then create a recipe to add food items from his own list then what is the food items missing here? I am asking about the meaning of this specific task in terms of feature implementation.
@mahammad-mostafa It will be the food items added but are not part of any recipe from that particular user.

**Comment by mahammad-mostafa** [comment]
Let me iterate what I have understood so far with you:
For example:
- User will create three food items (`apples` / `oranges` / `bananas`).
- User will create a recipe called `Fruit salad`.
- User will open details page and add only one food item for his list `apples`.
- The general shopping list will display two missing food items & their prices (`oranges` / `bananas`).
Correct me if I am wrong here.
 
Thanks a lot @danmainah for your help & cooperation.

**Comment by danmainah** [comment]
> Let me iterate what I have understood so far with you: For example:
> 
> * User will create three food items (`apples` / `oranges` / `bananas`).
> * User will create a recipe called `Fruit salad`.
> * User will open details page and add only one food item for his list `apples`.
> * The general shopping list will display two missing food items & their prices (`oranges` / `bananas`).
>   Correct me if I am wrong here.
> 
> Thanks a lot @danmainah for your help & cooperation.

@mahammad-mostafa Yeah you got it right

**Comment by ShadyShawkat** [comment]
## Hi @mahammad-mostafa , 

Your project is complete!  There is nothing else to say  :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
